In [1]:
import numpy as np

In [56]:
def determinant(A: np.ndarray):
    # A 为n*n的方阵
    if A.shape[0] == 1:
        return A[0, 0]
    if A.shape[0] == 2:
        return A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0]
    
    det = 0
    for j in range(A.shape[0]):
        sub_matrix = np.concatenate((A[1:, :j], A[1:, j+1:]), axis=1)
        det += (-1)**j * A[0, j] * determinant(sub_matrix)
    return det

def QR_decomposition(A: np.ndarray):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((m, n))
    
    for k in range(n):
        v = A[:, k]
        for j in range(k):
            R[j, k] = Q[:, j] @ A[:, k]
            v = v - R[j, k] * Q[:, j]
            
        R[k, k] = np.linalg.norm(v)
        Q[:, k] = v / R[k, k]
        
    return Q, R

def eigen_value(A: np.ndarray, max_iter=1000, tol=1e-8):
    # A 为n*n的方阵
    k = 0
    Ak = A.copy()
    Q_total = np.identity(A.shape[0])
    
    while k < max_iter:
        Q, R = QR_decomposition(Ak)
        Ak = R @ Q
        Q_total = Q_total @ Q
        
        # 判断收敛：是否接近上三角矩阵
        off = np.linalg.norm(Ak - np.triu(Ak))
        if off < tol:
            break
        k += 1
        
    eigvals = np.diag(Ak)
    
    return eigvals

def eigen_vector(A, eigvals, max_iter=10000, tol=1e-6):
    n = A.shape[0]
    alpha = 1e-3
    vectors = []
    
    for _lambda in eigvals:
        v = np.random.rand(n)
        v /= np.linalg.norm(v)
        
        for i in range(max_iter):
            grad = (A.T @ A - 2 * _lambda * A + _lambda ** 2 * np.identity(n)) @ v
            v -= alpha * grad
            v /= np.linalg.norm(v)
            
            # 判断收敛
            if np.linalg.norm(grad) < tol:
                break
            
        vectors.append(v)
    
    return np.array(vectors).T  # 每列是一个特征向量

A = np.array(
    [
        [1.,2.,3.,4.],
        [5.,6.,7.,8.],
        [9.,10.,11.,12.],
        [13.,14.,15.,16.]
    ]
)

eigvals = eigen_value(A)
eigvecs = eigen_vector(A, eigvals)
print(eigvecs)

np.linalg.eig(A)

[[-0.10998301 -0.71952174 -0.54077365  0.54748128]
 [ 0.20209456 -0.2747703   0.65620863 -0.71786324]
 [ 0.51417213  0.16998115  0.30990426 -0.20671795]
 [ 0.82624969  0.61473259 -0.4253392   0.37709986]]


EigResult(eigenvalues=array([ 3.62093727e+01, -2.20937271e+00, -3.18863232e-15, -1.34840081e-16]), eigenvectors=array([[-0.15115432,  0.72704996,  0.50370019, -0.06456091],
       [-0.34923733,  0.28320876, -0.8319577 , -0.31932112],
       [-0.54732033, -0.16063243,  0.15281481,  0.83232496],
       [-0.74540333, -0.60447363,  0.17544269, -0.44844294]]))

In [6]:
A = np.array(
    [
        [1.,2.,3.,4.],
        [5.,6.,7.,8.],
        [9.,10.,11.,12.],
        [13.,14.,15.,16.]
    ]
)

print(np.zeros(A.shape[0]))

[0. 0. 0. 0.]
